function output = importfile_ARS_table(filename, dataLines)
%IMPORTFILE Import data from a text file
%  ARS430HHCORNER5M = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a string
%  array.
%
%  ARS430HHCORNER5M = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  ars430HHcorner5m = importfile("X:\z_Projekte\öffentliche_F_und_E\aktuell\VIVALDI\11_RCS\2022-03_21_CARISSMA\05_Messung\01_Messdaten_roh\2022-03-21_Tests_trocken_vorher\01_corner_5m\ars430_HH_corner_5m.csv", [1, Inf]);
%
%  See also READMATRIX.
%
% Auto-generated by MATLAB on 16-Apr-2022 19:26:20

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 32);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["idx", "Detection", "Type", "UTCTimeStamp", "CycleCounter", "NoOfDetection", "Range", "RelativeRadialVelocity", "AzimuthAngle0", "AzimuthAngle1", "ElevationAngle", "RCS0", "RCS1", "Probability0", "Probability1", "RangeVariance", "VarianceRadVar", "AzimuthAngVar0", "AzimuthAngVar1", "ElevationAngVar", "pdh0", "SNR", "RangeExtent", "IntPowerlog", "VarName25", "VarName26", "VarName27", "VarName28", "VarName29", "VarName30", "VarName31", "VarName32"];
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["idx", "Detection", "Type", "UTCTimeStamp", "CycleCounter", "NoOfDetection", "Range", "RelativeRadialVelocity", "AzimuthAngle0", "AzimuthAngle1", "ElevationAngle", "RCS0", "RCS1", "Probability0", "Probability1", "RangeVariance", "VarianceRadVar", "AzimuthAngVar0", "AzimuthAngVar1", "ElevationAngVar", "pdh0", "SNR", "RangeExtent", "IntPowerlog", "VarName25", "VarName26", "VarName27", "VarName28", "VarName29", "VarName30", "VarName31", "VarName32"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["idx", "Detection", "Type", "UTCTimeStamp", "CycleCounter", "NoOfDetection", "Range", "RelativeRadialVelocity", "AzimuthAngle0", "AzimuthAngle1", "ElevationAngle", "RCS0", "RCS1", "Probability0", "Probability1", "RangeVariance", "VarianceRadVar", "AzimuthAngVar0", "AzimuthAngVar1", "ElevationAngVar", "pdh0", "SNR", "RangeExtent", "IntPowerlog", "VarName25", "VarName26", "VarName27", "VarName28", "VarName29", "VarName30", "VarName31", "VarName32"], "EmptyFieldRule", "auto");

% Import the data
output = readmatrix(filename, opts);

end